//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class frommail
    {
        public int ID { get; set; }
        public string FromEmailAdd { get; set; }
        public string Password { get; set; }
        public int IsDeleted { get; set; }
        public string username { get; set; }
        public string domain { get; set; }
    }
}
