//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LossDetail
    {
        public int Lid { get; set; }
        public int losscodeid { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public int MachineID { get; set; }
    }
}
