//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailmaster
    {
        public int ID { get; set; }
        public string EmailID { get; set; }
        public int TOAdd { get; set; }
        public int CCAdd { get; set; }
        public int IsDeleted { get; set; }
        public int BCCAdd { get; set; }
    }
}
