//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_history_master
    {
        public int MessageID { get; set; }
        public string Meassage { get; set; }
        public System.DateTime MessageDate { get; set; }
        public System.TimeSpan MessageTime { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public string MessageNo { get; set; }
        public string MessageCode { get; set; }
        public string MessageType { get; set; }
        public string MessageShift { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public Nullable<int> IsProgLock { get; set; }
    }
}
