//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcbdps_master
    {
        public int PcbDpsMasterID { get; set; }
        public Nullable<int> Pin17 { get; set; }
        public Nullable<int> Pin18 { get; set; }
        public Nullable<int> Pin19 { get; set; }
        public Nullable<int> Pin20 { get; set; }
        public Nullable<int> Pin22 { get; set; }
        public Nullable<int> Pin23 { get; set; }
        public Nullable<int> Pin24 { get; set; }
        public Nullable<int> Pin25 { get; set; }
        public Nullable<int> Pin26 { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string ColorValue { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
