//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class program_master
    {
        public int ProgramID { get; set; }
        public string EmployeeCode { get; set; }
        public string ComponentDescription { get; set; }
        public string ComponentCode { get; set; }
        public string OperationDescription { get; set; }
        public string WorkOrderNo1 { get; set; }
        public string WorkOrderNo2 { get; set; }
        public string WorkOrderNo3 { get; set; }
        public int MachineID { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public System.DateTime ProgramDate { get; set; }
        public System.TimeSpan ProgramTime { get; set; }
        public System.DateTime ProgramDateTime { get; set; }
        public string OpnCode1 { get; set; }
        public int PartsProduced1 { get; set; }
        public int PartsAccepted1 { get; set; }
        public string OpnCode2 { get; set; }
        public Nullable<int> PartsProduced2 { get; set; }
        public Nullable<int> PartsAccepted2 { get; set; }
        public string OpnCode3 { get; set; }
        public Nullable<int> PartsProduced3 { get; set; }
        public Nullable<int> PartsAccepted3 { get; set; }
        public string Shift { get; set; }
        public Nullable<int> PartsRejected1 { get; set; }
        public Nullable<int> PartsRejected2 { get; set; }
        public Nullable<int> PartsRejected3 { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
    }
}
