//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sharathtable
    {
        public int sharathid { get; set; }
        public string sharathname { get; set; }
        public Nullable<int> sharathvalue { get; set; }
        public bool syncid { get; set; }
        public int MCID { get; set; }
        public int TabSharathID { get; set; }
    }
}
