//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_oeereportasdivision
    {
        public int LID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string FGCode { get; set; }
        public Nullable<int> LossID { get; set; }
        public long LossDuration { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
