//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProdManMachine
    {
        public int ProdManMachineID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime CorrectedDate { get; set; }
        public int WOID { get; set; }
        public Nullable<decimal> UtilPercent { get; set; }
        public decimal TotalLoss { get; set; }
        public decimal TotalSetup { get; set; }
        public decimal TotalMinorLoss { get; set; }
        public decimal TotalOperatingTime { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public decimal TotalSetupMinorLoss { get; set; }
        public decimal TotalPowerLoss { get; set; }
        public decimal PerformancePerCent { get; set; }
        public decimal QualityPercent { get; set; }
        public int PerfromaceFactor { get; set; }
    
        public virtual tblmachinedetail tblmachinedetail { get; set; }
        public virtual tblworkorderentry tblworkorderentry { get; set; }
    }
}
