//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProdOrderLosses
    {
        public int ProdOrderlossID { get; set; }
        public int WOID { get; set; }
        public int LossID { get; set; }
        public long LossDuration { get; set; }
        public System.DateTime CorrectedDate { get; set; }
        public int LossCodeL1ID { get; set; }
        public Nullable<int> LossCodeL2ID { get; set; }
        public int MachineID { get; set; }
    
        public virtual tblmachinedetail tblmachinedetail { get; set; }
    }
}
