//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblapp_paths
    {
        public int AppPathsID { get; set; }
        public string AppName { get; set; }
        public string AppPath { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
