//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        public int CID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerShortName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int Landline1 { get; set; }
        public Nullable<int> Landline2 { get; set; }
        public string EmailID1 { get; set; }
        public string EmailID2 { get; set; }
        public Nullable<int> Fax { get; set; }
        public byte[] Logo { get; set; }
        public string Website { get; set; }
        public string CPName { get; set; }
        public string CPDesignation { get; set; }
        public string CPDepartment { get; set; }
        public string CPEmailID { get; set; }
        public Nullable<int> CPMobileNO { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
