//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhistpm
    {
        public int id { get; set; }
        public int Machineid { get; set; }
        public int pmsid { get; set; }
        public int Pmcheckpointid { get; set; }
        public string Pmchecklistname { get; set; }
        public Nullable<int> workdone { get; set; }
        public string Remarks { get; set; }
        public string CorrectedDate { get; set; }
        public int Cellid { get; set; }
    }
}
