//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmodulemaster
    {
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] IsSuperAdmin { get; set; }
        public byte[] EnableReport { get; set; }
        public byte[] EnableAdd { get; set; }
        public byte[] EnableEdit { get; set; }
        public byte[] EnableDelete { get; set; }
        public Nullable<int> RoleID { get; set; }
    }
}
