//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmodulehelper
    {
        public int ID { get; set; }
        public string ModuleID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public byte[] IsAll { get; set; }
        public byte[] IsAdded { get; set; }
        public byte[] IsEdited { get; set; }
        public byte[] IsRemoved { get; set; }
        public byte[] IsReadonly { get; set; }
        public byte[] IsHidden { get; set; }
        public short IsDeleted { get; set; }
    }
}
