//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloperatordetail
    {
        public int OPID { get; set; }
        public string Dept { get; set; }
        public string OperatorName { get; set; }
        public string OperatorID { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> CorrectedDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> OperatorDesc { get; set; }
        public string operatorMailId { get; set; }
        public string contactNo { get; set; }
        public string employeeId { get; set; }
    }
}
