//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblworkmodemimic
    {
        public int WMID { get; set; }
        public int OperatingTime { get; set; }
        public int Delay { get; set; }
        public int Alarm { get; set; }
        public int MDI { get; set; }
        public int JOG { get; set; }
        public int HND { get; set; }
        public int EDIT { get; set; }
        public int RTN { get; set; }
        public int ETC { get; set; }
        public int PowerOff { get; set; }
        public int MachineOnTime { get; set; }
        public int MachineID { get; set; }
        public string Shift { get; set; }
        public string CorrectedDate { get; set; }
    
        public virtual tblmachinedetail tblmachinedetail { get; set; }
    }
}
